name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci
      working-directory: ./back

    - name: Build
      run: DB_USERNAME=${{ secrets.DB_USERNAME }} && DB_PASSWORD=${{ secrets.DB_PASSWORD }} && DB_DATABASE=${{ secrets.DB_DATABASE }} && DB_HOST=${{ secrets.DB_HOST }} && DB_DIALECT=${{ secrets.DB_DIALECT }} && DB_SYNC_MODE_FORCE=${{ secrets.DB_SYNC_MODE_FORCE }} && npm run build
      working-directory: ./back

    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./back
        remote: back/build/
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.USER_PASS }}
        env: |
          DB_USERNAME=${{ secrets.DB_USERNAME }} 
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          DB_SYNC_MODE_FORCE=${{ secrets.DB_SYNC_MODE_FORCE }}