name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: #for Create release branch
      contents: write

    steps:
    - name: Set env
      run: echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Build project
      run: npm run build
      working-directory: ./web

    - name: Deploy to Vercel
      run: npx vercel --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
