name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: #for Create release branch
      contents: write

    steps:
    - name: Set env
      run: echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Create configuration file
      run: |
        echo "RECONNECT_TRIES=${{ secrets.RECONNECT_TRIES }} 
        SERVER_URL=${{ secrets.SERVER_URL }}" > .env
      working-directory: ./web

    - name: Build project
      run: npm run build
      working-directory: ./web

    - name: Install Vercel CLI
      run: npm install --global vercel@canary
      working-directory: ./web
    
    - name: Create .vercel/output directory
      run: mkdir -p .vercel/output

    - name: Move build output to .vercel/output
      run: mv ./web/dist/* .vercel/output/

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Make sure to set this in your repository secrets
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prebuilt'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # If you're in a team/organization
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # If you have a specific project ID
        working-directory: ./.vercel/output/

 