name: Test auth with server

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  check-auth:

    runs-on: ubuntu-latest
    steps:

      - name: Add S SH private key
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")